### ISSUE TITLE
404 from twitter when i'm  trying your example

### ISSUE THREAD

**Issue by Bramichou** [kevva/instagram-posts#2]
![capture d ecran 2018-07-07 a 14 52 39](https://user-images.githubusercontent.com/23286738/42411063-6d0ad4e8-81f5-11e8-9d93-f0e8c4d44155.png)

What am i suppose to do ?

**Comment by StevenPartridge** [comment]
Also having this issue. Perhaps related to recent instagram api limitations?

**Comment by lnorton89** [comment]
Am also getting this error.

**Comment by StevenPartridge** [comment]
After doing some research I've found out that the api calls this package uses (/media) have been deprecated by Instagram. The rest of their public facing apis are going to be deprecated by early 2020. In order to get media from an instagram account after that we will need to use the graph api

**Comment by Bramichou** [comment]
Yes i saw, so never mind to use that tool instagram-post, will be deprecated... Thank you btw ! Hope you will make ur own instagram post lib maybe 👍 for my self, will stop here, and will see at insta doc 😄
